# Generated by Django 5.2.8 on 2025-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0006_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="labels",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="labels", to="task_manager.tasks"
            ),
        ),
    ]
