# Generated by Django 5.2.8 on 2025-11-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0007_labels_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="labels",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="statuses",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authored_tasks",
                to="task_manager.users",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executed_tasks",
                to="task_manager.users",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="task_manager.statuses",
                verbose_name="Статус",
            ),
        ),
    ]
