# Generated by Django 5.2.8 on 2025-11-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="autor",
        ),
        migrations.AddField(
            model_name="tasks",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authored_tasks",
                to="task_manager.users",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executed_tasks",
                to="task_manager.users",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="task_manager.statuses",
            ),
        ),
    ]
